version: '3'
services:
  web:
    build: .
    container_name: python-fastapi-test
    external_links:
      - postgres:postgres
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
  database:
    image: "postgres"
    container_name: postgres
    ports:
      - "5432:5432"