version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=practice
    networks:
      - mnetwork
    command:
      - postgres
      - -c
      - wal_level=logical

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - mnetwork

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - mnetwork
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.2.3
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    networks:
      - mnetwork
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    depends_on:
      - pgsync
    networks:
      - mnetwork

  pgsync:
    build: .
    command:
      - bash
      - -c
      - |
        while !</dev/tcp/elasticsearch/9200; do sleep 1; done; \
        bootstrap
        pgsync  --config /app/schema.json --daemon > /dev/null
    environment: 
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_PASSWORD=postgres
      - ELASTICSEARCH_HOST=localhost
      - ELASTICSEARCH_PORT=9200
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    networks:
      - mnetwork
    depends_on:
      - elasticsearch
      - postgres

networks:
  mnetwork:
    driver: bridge